services:
  - type: web
    name: noiratelier-frontend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    plan: free
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
